//! Version-aware `server.properties` schema (`data/server-properties.json`).
//!
//! Rule: once a server has generated its `server.properties`, the file itself is the
//! authority on which keys that version supports (Minecraft writes every key it knows).
//! The schema only adds metadata (type, category, help). Before the first start, schema
//! entries are filtered by `since`/`until` using the Mojang release order.

use super::properties::PropertiesDocument;
use crate::error::{CoreError, CoreResult};
use crate::software::VersionCatalog;
use serde::{Deserialize, Serialize};
use std::sync::LazyLock;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PropertyType {
    Boolean,
    Integer,
    String,
    /// Free text shown in a larger input (motd).
    Text,
    Enum,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PropertyCategory {
    Gameplay,
    Network,
    World,
    Performance,
    Security,
    Advanced,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertySchema {
    pub key: String,
    #[serde(rename = "type")]
    pub kind: PropertyType,
    #[serde(default)]
    pub values: Vec<String>,
    #[serde(default)]
    pub suggestions: Vec<String>,
    pub min: Option<i64>,
    pub max: Option<i64>,
    pub default: Option<String>,
    pub category: PropertyCategory,
    pub label: String,
    pub description: Option<String>,
    pub since: Option<String>,
    pub until: Option<String>,
    #[serde(default)]
    pub sensitive: bool,
}

#[derive(Debug, Deserialize)]
struct SchemaFile {
    properties: Vec<PropertySchema>,
}

static SCHEMA: LazyLock<Vec<PropertySchema>> = LazyLock::new(|| {
    let raw = include_str!("../../../../data/server-properties.json");
    match serde_json::from_str::<SchemaFile>(raw) {
        Ok(f) => f.properties,
        Err(e) => {
            tracing::error!("invalid server-properties.json: {e}");
            Vec::new()
        }
    }
});

pub fn all_schemas() -> &'static [PropertySchema] {
    &SCHEMA
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Applicability {
    /// Known to apply to this version.
    Applies,
    /// Could not determine (unknown version ordering).
    Unknown,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PropertyView {
    pub key: String,
    /// Current value; `None` for sensitive keys (write-only) or keys not in the file.
    pub value: Option<String>,
    pub present: bool,
    pub has_value: bool,
    pub schema: Option<PropertySchema>,
    pub applicability: Applicability,
}

/// Minimum entries for a file to count as "generated by the server".
const GENERATED_THRESHOLD: usize = 10;

async fn applies(schema: &PropertySchema, version: &str, catalog: &VersionCatalog) -> Option<bool> {
    let since_ok = match &schema.since {
        None => Some(true),
        Some(s) => catalog.is_at_least(version, s).await,
    };
    let until_ok = match &schema.until {
        None => Some(true),
        Some(u) => catalog.is_at_least(version, u).await.map(|b| !b),
    };
    match (since_ok, until_ok) {
        (Some(a), Some(b)) => Some(a && b),
        _ => None,
    }
}

/// Pick the schema variant for `key` that applies to `version` (first match wins).
pub async fn schema_for(
    key: &str,
    version: &str,
    catalog: &VersionCatalog,
) -> Option<(PropertySchema, Applicability)> {
    let variants: Vec<&PropertySchema> = SCHEMA.iter().filter(|s| s.key == key).collect();
    let mut unknown = None;
    for v in &variants {
        match applies(v, version, catalog).await {
            Some(true) => return Some(((*v).clone(), Applicability::Applies)),
            Some(false) => {}
            None => {
                if unknown.is_none() {
                    unknown = Some((*v).clone());
                }
            }
        }
    }
    unknown.map(|s| (s, Applicability::Unknown)).or_else(|| {
        variants
            .first()
            .map(|s| ((*s).clone(), Applicability::Unknown))
    })
}

pub async fn describe(
    doc: &PropertiesDocument,
    version: &str,
    catalog: &VersionCatalog,
) -> Vec<PropertyView> {
    let entries = doc.entries();
    let generated = entries.len() >= GENERATED_THRESHOLD;
    let mut out = Vec::new();
    for (key, value) in &entries {
        let found = schema_for(key, version, catalog).await;
        let sensitive = found.as_ref().is_some_and(|(s, _)| s.sensitive);
        out.push(PropertyView {
            key: key.clone(),
            value: (!sensitive).then(|| value.clone()),
            present: true,
            has_value: !value.is_empty(),
            applicability: found.as_ref().map_or(Applicability::Applies, |(_, a)| *a),
            schema: found.map(|(s, _)| s),
        });
    }
    if !generated {
        let mut seen: Vec<String> = entries.iter().map(|(k, _)| k.clone()).collect();
        for s in SCHEMA.iter() {
            if seen.contains(&s.key) {
                continue;
            }
            match applies(s, version, catalog).await {
                Some(true) => {}
                Some(false) => continue,
                None if s.since.is_some() || s.until.is_some() => continue,
                None => {}
            }
            seen.push(s.key.clone());
            out.push(PropertyView {
                key: s.key.clone(),
                value: None,
                present: false,
                has_value: false,
                schema: Some(s.clone()),
                applicability: Applicability::Applies,
            });
        }
    }
    out
}

/// Validate a value against its schema. Unknown keys accept any single-line-safe value.
pub fn validate_value(schema: Option<&PropertySchema>, key: &str, value: &str) -> CoreResult<()> {
    if value.len() > 32 * 1024 {
        return Err(CoreError::invalid(format!("Value for '{key}' is too long")));
    }
    let Some(s) = schema else { return Ok(()) };
    match s.kind {
        PropertyType::Boolean => {
            if value != "true" && value != "false" {
                return Err(CoreError::invalid(format!(
                    "'{}' must be true or false",
                    s.label
                )));
            }
        }
        PropertyType::Integer => {
            let n: i64 = value
                .trim()
                .parse()
                .map_err(|_| CoreError::invalid(format!("'{}' must be a whole number", s.label)))?;
            if s.min.is_some_and(|m| n < m) || s.max.is_some_and(|m| n > m) {
                return Err(CoreError::invalid(format!(
                    "'{}' must be between {} and {}",
                    s.label,
                    s.min.map_or("-∞".into(), |m| m.to_string()),
                    s.max.map_or("∞".into(), |m| m.to_string())
                )));
            }
        }
        PropertyType::Enum => {
            if !s.values.iter().any(|v| v == value) {
                return Err(CoreError::invalid(format!(
                    "'{}' must be one of: {}",
                    s.label,
                    s.values.join(", ")
                )));
            }
        }
        PropertyType::String | PropertyType::Text => {}
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_loads_and_is_consistent() {
        assert!(SCHEMA.len() > 40);
        for s in SCHEMA.iter() {
            if s.kind == PropertyType::Enum {
                assert!(!s.values.is_empty(), "{} has no enum values", s.key);
            }
            if let Some(d) = &s.default {
                validate_value(Some(s), &s.key, d)
                    .unwrap_or_else(|e| panic!("default of {}: {}", s.key, e.message));
            }
        }
    }

    #[test]
    fn validation() {
        let s = SCHEMA.iter().find(|s| s.key == "view-distance").unwrap();
        assert!(validate_value(Some(s), "view-distance", "12").is_ok());
        assert!(validate_value(Some(s), "view-distance", "1").is_err());
        assert!(validate_value(Some(s), "view-distance", "abc").is_err());
        let b = SCHEMA.iter().find(|s| s.key == "pvp").unwrap();
        assert!(validate_value(Some(b), "pvp", "yes").is_err());
    }

    #[tokio::test]
    async fn sensitive_values_are_hidden_and_unknown_keys_kept() {
        let catalog = VersionCatalog::new(None);
        let doc =
            PropertiesDocument::parse("rcon.password=hunter2\ncustom-plugin-key=1\nmotd=Hi\n");
        let views = describe(&doc, "1.21.4", &catalog).await;
        let rcon = views.iter().find(|v| v.key == "rcon.password").unwrap();
        assert_eq!(rcon.value, None);
        assert!(rcon.has_value);
        let custom = views.iter().find(|v| v.key == "custom-plugin-key").unwrap();
        assert!(custom.schema.is_none());
        assert_eq!(custom.value.as_deref(), Some("1"));
        // Without version ordering, versioned keys are not offered for a fresh file.
        assert!(!views.iter().any(|v| v.key == "simulation-distance"));
        assert!(views.iter().any(|v| v.key == "view-distance" && !v.present));
    }
}
