// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountProfileDto = { uid: string, email: string | null, emailVerified: boolean, displayName: string | null, photoUrl: string | null, 
/**
 * "password" | "google.com"
 */
provider: string, };
