// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountProfileDto } from "./AccountProfileDto";

export type AccountDto = { 
/**
 * A Firebase project is configured in this build.
 */
configured: boolean, googleAvailable: boolean, microsoftAvailable: boolean, signedIn: boolean, isGuest: boolean, profile: AccountProfileDto | null, 
/**
 * "waiting" | "done" | "failed" for a Google sign-in started in MCPanel.
 */
googleState: string | null, googleError: string | null, 
/**
 * "waiting" | "done" | "failed" for a Microsoft sign-in started in MCPanel.
 */
microsoftState: string | null, microsoftError: string | null, customOauthConfigured: boolean, };
