// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddHostDto = { name: string, endpoint: string, authToken: string | null, tags: Array<string>, };
