// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiPendingConfirmationDto } from "./AiPendingConfirmationDto";
import type { AiToolExecutionDto } from "./AiToolExecutionDto";

export type AiChatMessageDto = { id: string, role: string, content: string, timestamp: number, pendingConfirmation: AiPendingConfirmationDto | null, toolExecutions: Array<AiToolExecutionDto> | null, };
