// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiChatMessageDto } from "./AiChatMessageDto";

export type AiConfirmRequestDto = { confirmationId: string, approved: boolean, messages: Array<AiChatMessageDto>, serverId: string | null, };
