// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiConfigPatchDto = { apiKey: string | null, provider: string | null, model: string | null, baseUrl: string | null, };
