// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiToolExecutionDto = { tool: string, description: string, isMajor: boolean, result: string | null, error: string | null, };
