// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ApiError = { 
/**
 * Stable code, e.g. `SERVER_NOT_FOUND` (see `mcpanel_core::ErrorCode`).
 */
code: string, message: string, details: JsonValue | null, retryable: boolean, };
