// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfoDto = { version: string, platform: string, dataDir: string, defaultServersDir: string, logsDir: string, };
