// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AuditEntryDto = { id: string, occurredAt: number, actor: string, action: string, serverId: string | null, target: string | null, 
/**
 * "success" | "failure"
 */
result: string, metadata: JsonValue, };
