// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupPolicyUpdateDto = { enabled: boolean, intervalMinutes: number, skipIfIdle: boolean, keepLast: number, keepDaily: number, keepWeekly: number, keepMonthly: number, maxTotalGb: number, };
