// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupLocationDto = { directory: string, isDefault: boolean, defaultDirectory: string, 
/**
 * Free space on the drive, when the folder exists.
 */
availableBytes: number | null, warnings: Array<string>, };
