// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupPolicyDto = { serverId: string, enabled: boolean, intervalMinutes: number, skipIfIdle: boolean, keepLast: number, keepDaily: number, keepWeekly: number, keepMonthly: number, 
/**
 * GiB; 0 = no cap.
 */
maxTotalGb: number, lastRunAt: number | null, 
/**
 * When the scheduler next considers this server (if enabled).
 */
nextRunAt: number | null, };
