// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedFileDto } from "./SkippedFileDto";

export type BackupDto = { id: string, serverId: string | null, serverName: string, 
/**
 * "manual" | "scheduled" | "pre_restore"
 */
kind: string, 
/**
 * "creating" | "ready" | "failed"
 */
status: string, path: string, fileName: string, filePresent: boolean, createdAt: number, finishedAt: number | null, sizeBytes: number, contentBytes: number, fileCount: number, live: boolean, containsSensitive: boolean, softwareId: string, gameVersion: string, note: string | null, protected: boolean, skipped: Array<SkippedFileDto>, errorMessage: string | null, };
