// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BanDto = { 
/**
 * Player name, or the IP address for IP bans.
 */
target: string, uuid: string | null, reason: string | null, source: string | null, created: string | null, 
/**
 * `null` = permanent.
 */
expires: string | null, };
