// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockPieceDto } from "./BedrockPieceDto";
import type { BedrockSettingsDto } from "./BedrockSettingsDto";

export type BedrockStatusDto = { supported: boolean, unsupportedReason: string | null, geyser: BedrockPieceDto | null, floodgate: BedrockPieceDto | null, viaVersion: BedrockPieceDto | null, viaVersionAvailable: boolean, viaVersionSuggested: boolean, viaVersionRequired: boolean, configPath: string | null, configExists: boolean, settings: BedrockSettingsDto, activePort: number | null, running: boolean, restartRequired: boolean, floodgateKeyPresent: boolean, 
/**
 * Another program holds the Bedrock UDP port (checked while stopped).
 */
portInUse: boolean, portInUseBy: string | null, defaultPort: number, };
