// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockPongDto = { motd: string, subMotd: string | null, version: string, protocol: number | null, players: number | null, maxPlayers: number | null, gameMode: string | null, latencyMs: number, };
