// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockPieceDto = { fileName: string, version: string | null, enabled: boolean, pending: boolean, };
