// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockEnableDto = { floodgate: boolean, viaVersion: boolean, port: number | null, };
