// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudStatusDto = { 
/**
 * "google_drive" | "onedrive" | "dropbox"
 */
id: string, displayName: string, configured: boolean, clientIdVariable: string, connected: boolean, needsReconnect: boolean, accountName: string | null, accountEmail: string | null, connectedAt: number | null, scopes: Array<string>, redirectUris: Array<string>, manageAccessUrl: string, };
