// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudOperationDto = { id: string, provider: string, backupId: string | null, backupName: string, 
/**
 * "upload" | "download" | "restore"
 */
opType: string, 
/**
 * "idle" | "starting" | "uploading" | "downloading" | "processing" | "cancelling" | "cancelled" | "completed" | "failed"
 */
state: string, bytesCompleted: number, totalBytes: number | null, percentage: number | null, startedAtMs: number, bytesPerSec: number | null, etaSeconds: number | null, errorMessage: string | null, };
