// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CloudFileDto = { id: string, provider: string, name: string, sizeBytes: number, createdAt: number | null, modifiedAt: number | null, };
