// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsoleLineDto = { seq: number, at: number, 
/**
 * "stdout" | "stderr" | "system" | "command"
 */
stream: string, 
/**
 * "trace" | "debug" | "info" | "warn" | "error" | "fatal"
 */
level: string | null, text: string, };
