// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleLineDto } from "./ConsoleLineDto";

export type ConsoleBatchDto = { lines: Array<ConsoleLineDto>, 
/**
 * Inclusive range of sequence numbers that were dropped (buffer overflow).
 */
gapFrom: number | null, gapTo: number | null, };
