// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDependencyDto } from "./ContentDependencyDto";

export type ContentVersionDto = { provider: string, projectId: string, id: string, name: string, versionNumber: string, 
/**
 * "release" | "beta" | "alpha"
 */
channel: string, gameVersions: Array<string>, published: number | null, fileName: string | null, sizeBytes: number | null, 
/**
 * "sha512" | "sha256" | "sha1"; `null` = unverified.
 */
hashAlgorithm: string | null, externalUrl: string | null, dependencies: Array<ContentDependencyDto>, };
