// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentEntryDto } from "./ContentEntryDto";
import type { ContentProviderDto } from "./ContentProviderDto";
import type { PendingChangeDto } from "./PendingChangeDto";

export type ContentListDto = { 
/**
 * "plugin" | "mod"
 */
kind: string, folder: string, running: boolean, entries: Array<ContentEntryDto>, pending: Array<PendingChangeDto>, providers: Array<ContentProviderDto>, };
