// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentEntryDto = { fileName: string, enabled: boolean, sizeBytes: number, 
/**
 * Name from MCPanel's record or the jar's descriptor.
 */
name: string, version: string | null, 
/**
 * e.g. `plugin.yml`; `null` = no descriptor found.
 */
descriptorFormat: string | null, provider: string | null, projectId: string | null, versionId: string | null, 
/**
 * Queued change: "install" | "remove" | "disable" | "enable".
 */
pending: string | null, };
