// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentDependencyDto = { projectId: string | null, name: string | null, 
/**
 * "required" | "optional" | "incompatible" | "embedded"
 */
kind: string, externalUrl: string | null, };
