// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuspectDto } from "./SuspectDto";

export type CrashEventDto = { id: string, occurredAt: number, exitCode: number | null, kind: string, message: string, attempt: number, 
/**
 * "restart" | "gave_up" | "not_restartable" | "disabled"
 */
action: string, restartAt: number | null, crashReport: string | null, consoleTail: Array<string>, 
/**
 * Root-cause exception, if one was found.
 */
exception: string | null, 
/**
 * Plugins/mods in the crashing code path, most likely first.
 */
suspects: Array<SuspectDto>, };
