// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyValueDto } from "./PropertyValueDto";

export type CreateServerDto = { name: string, 
/**
 * Grant token for a parent folder; `null` = default servers folder.
 */
parentDirectoryGrant: string | null, softwareId: string, gameVersion: string, build: string | null, javaRuntimeId: string, minMemoryMb: number, maxMemoryMb: number, jvmArgs: Array<string>, properties: Array<PropertyValueDto>, 
/**
 * The user ticked "I accept the Minecraft EULA".
 */
acceptEula: boolean, };
