// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedSoftwareDto = { softwareId: string, gameVersion: string | null, build: string | null, jar: string, confidence: number, };
