// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectedPluginDto = { fileName: string, name: string, version: string | null, provider: string | null, projectId: string | null, platform: string | null, 
/**
 * "exact" | "high" | "medium" | "low" | "unknown"
 */
confidence: string, description: string | null, };
