// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskDto = { mountPoint: string, name: string, totalBytes: number, availableBytes: number, removable: boolean, };
