// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskUsageDto = { totalBytes: number, worldsBytes: number, contentBytes: number, logsBytes: number, otherBytes: number, 
/**
 * This server's backups (all kinds).
 */
backupsBytes: number, 
/**
 * Free space on the server's drive.
 */
driveFreeBytes: number | null, driveTotalBytes: number | null, truncated: boolean, };
