// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EncryptionStatusDto = { configured: boolean, 
/**
 * Public key (`age1…`); identifies which Recovery Kit belongs to it.
 */
recipient: string | null, createdAt: number | null, encryptBackups: boolean, keyAvailable: boolean, minPassphraseChars: number, };
