// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileEntryDto = { name: string, path: string, 
/**
 * "file" | "directory" | "link"
 */
kind: string, size: number | null, modified: number | null, 
/**
 * Protected key material (e.g. Floodgate key): content is never exposed.
 */
sensitive: boolean, readonly: boolean, };
