// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntryDto } from "./FileEntryDto";

export type FileOpResultDto = { files: number, bytes: number, skippedLinks: number, skippedSensitive: number, entry: FileEntryDto | null, };
