// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameVersionDto = { id: string, 
/**
 * "release" | "snapshot" | "old_beta" | "old_alpha"
 */
kind: string, releaseTime: number | null, };
