// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrantDto = { token: string, 
/**
 * Shown to the user; never sent back.
 */
displayPath: string, name: string, };
