// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostPingResultDto = { hostId: string, online: boolean, latencyMs: number | null, message: string | null, };
