// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostEnrollmentTokenDto = { token: string, accountUid: string, expiresAt: number, pairingCommand: string, };
