// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HostDto = { id: string, name: string, endpoint: string | null, isLocal: boolean, status: string, tags: Array<string>, osInfo: string | null, cpuCount: number | null, totalMemoryBytes: number | null, usedMemoryBytes: number | null, serversCount: number, runningServersCount: number, latencyMs: number | null, lastSeen: number | null, createdAt: number, };
