// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentifyContentRequestDto = { fileName: string, provider: string, projectId: string, versionNumber: string | null, name: string | null, };
