// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedSoftwareDto } from "./DetectedSoftwareDto";

export type ImportDetectionDto = { detected: DetectedSoftwareDto | null, hasEula: boolean, hasProperties: boolean, jars: Array<string>, warnings: Array<string>, directory: string, };
