// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportServerDto = { name: string, directoryGrant: string, softwareId: string | null, gameVersion: string | null, jar: string | null, javaRuntimeId: string | null, minMemoryMb: number, maxMemoryMb: number, };
