// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaCompatibilityEntryDto } from "./JavaCompatibilityEntryDto";

export type InstallPreviewDto = { softwareId: string, gameVersion: string, build: string | null, buildChannel: string | null, javaMinMajor: number, javaRecommendedMajor: number | null, recommendedJvmFlags: Array<string>, notes: Array<string>, 
/**
 * e.g. "sha256"; `null` if the provider publishes no checksum.
 */
hashAlgorithm: string | null, 
/**
 * SHA-256/SHA-512 = strong; SHA-1/MD5 = integrity only.
 */
hashStrong: boolean, downloadBytes: number | null, java: Array<JavaCompatibilityEntryDto>, };
