// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlannedInstallDto } from "./PlannedInstallDto";

export type InstallPlanDto = { items: Array<PlannedInstallDto>, unresolved: Array<string>, warnings: Array<string>, deferred: boolean, };
