// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JavaCompatibilityDto } from "./JavaCompatibilityDto";

export type JavaCompatibilityEntryDto = { javaRuntimeId: string, compatibility: JavaCompatibilityDto, };
