// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaRuntimeDto = { id: string, path: string, major: number, version: string, vendor: string | null, arch: string | null, is64bit: boolean, 
/**
 * "detected" | "manual" | "managed"
 */
source: string, valid: boolean, validationError: string | null, validatedAt: number, };
