// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaCompatibilityDto = { "status": "compatible" } | { "status": "too_old", required: number, } | { "status": "newer_than_recommended", recommended: number, } | { "status": "not_validated" };
