// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type JobDto = { id: string, kind: string, serverId: string | null, 
/**
 * "queued" | "running" | "succeeded" | "failed" | "cancelled"
 */
status: string, progress: number | null, message: string | null, createdAt: number, finishedAt: number | null, errorCode: string | null, errorMessage: string | null, result: JsonValue | null, };
