// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnownPlayerDto = { name: string, uuid: string | null, online: boolean, opLevel: number | null, whitelisted: boolean, banned: boolean, firstSeen: number | null, lastSeen: number | null, totalPlayMs: number | null, sessions: number | null, };
