// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchConfigDto = { javaRuntimeId: string | null, minMemoryMb: number, maxMemoryMb: number, jvmArgs: Array<string>, serverArgs: Array<string>, stopTimeoutSecs: number, };
