// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocationCheckDto = { directory: string, 
/**
 * "one_drive_synced" | "network_drive" | ...
 */
warnings: Array<string>, };
