// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostDto } from "./HostDto";

export type MultihostStatusDto = { accountRequired: boolean, signedIn: boolean, userEmail: string | null, hosts: Array<HostDto>, };
