// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationDto = { id: string, createdAt: number, serverId: string | null, 
/**
 * "crash" | "backup_failed" | "task_failed" | "player_joined"
 */
category: string, 
/**
 * "info" | "success" | "warning" | "error"
 */
severity: string, title: string, body: string, read: boolean, };
