// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelsDto } from "./ChannelsDto";

export type NotificationPrefsDto = { crash: ChannelsDto, backupFailed: ChannelsDto, taskFailed: ChannelsDto, playerJoined: ChannelsDto, diskLow: ChannelsDto, };
