// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PendingChangeDto = { id: string, 
/**
 * "install" | "remove" | "disable" | "enable"
 */
action: string, fileName: string, name: string, version: string | null, createdAt: number, };
