// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentVersionDto } from "./ContentVersionDto";
import type { ProjectDto } from "./ProjectDto";

export type PlannedInstallDto = { project: ProjectDto, version: ContentVersionDto, replaces: string | null, requiredBy: string | null, };
