// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayitAgentDto = { 
/**
 * The playit program (with playitd.exe) is installed.
 */
installed: boolean, linked: boolean, 
/**
 * "waiting" | "linked" | "failed" for a link started in MCPanel.
 */
linkState: string | null, linkUrl: string | null, linkError: string | null, running: boolean, phase: string | null, autostart: boolean, };
