// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A player-management action. Names and reasons are validated by the core.
 */
export type PlayerActionDto = { "action": "op", name: string, } | { "action": "deop", name: string, } | { "action": "whitelist_add", name: string, } | { "action": "whitelist_remove", name: string, } | { "action": "set_whitelist", enabled: boolean, } | { "action": "ban", name: string, reason: string | null, } | { "action": "pardon", name: string, } | { "action": "ban_ip", ip: string, reason: string | null, } | { "action": "pardon_ip", ip: string, } | { "action": "kick", name: string, reason: string | null, };
