// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayitTunnelDto } from "./PlayitTunnelDto";

export type PlayitTunnelsDto = { agentId: string, 
/**
 * "guest" | "email-not-verified" | "verified"
 */
accountStatus: string, premium: boolean, tunnels: Array<PlayitTunnelDto>, };
