// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayitTunnelDto = { id: string, name: string | null, 
/**
 * "minecraft-java" | "minecraft-bedrock" | other playit types; null for custom ports.
 */
tunnelType: string | null, portType: string, enabled: boolean, offlineReasons: Array<string>, localIp: string | null, localPort: number | null, addresses: Array<string>, 
/**
 * Belongs to MCPanel's agent, so MCPanel may change it.
 */
editable: boolean, };
