// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginRecommendationDto = { id: string, name: string, description: string, category: string, provider: string, projectId: string, iconUrl: string | null, reason: string, };
