// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProcessUsageDto = { cpuPercent: number, memoryBytes: number, processCount: number, };
