// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDto = { provider: string, id: string, slug: string, name: string, description: string, author: string | null, downloads: number, iconUrl: string | null, pageUrl: string, updated: number | null, license: string | null, };
