// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertySchemaDto } from "./PropertySchemaDto";

export type PropertyDto = { key: string, 
/**
 * `null` for sensitive keys (write-only) or keys not in the file.
 */
value: string | null, present: boolean, hasValue: boolean, 
/**
 * "applies" | "unknown"
 */
applicability: string, schema: PropertySchemaDto | null, };
