// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PropertyChangeDto = { key: string, 
/**
 * `null` removes the key.
 */
value: string | null, };
