// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PropertySchemaDto = { 
/**
 * "boolean" | "integer" | "string" | "text" | "enum"
 */
kind: string, values: Array<string>, suggestions: Array<string>, min: number | null, max: number | null, default: string | null, 
/**
 * "gameplay" | "network" | "world" | "performance" | "security" | "advanced"
 */
category: string, label: string, description: string | null, sensitive: boolean, };
