// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryRangeDto } from "./MemoryRangeDto";
import type { TemplatePluginDto } from "./TemplatePluginDto";
import type { TemplatePropertyDto } from "./TemplatePropertyDto";

export type ResolvedTemplateDto = { templateId: string, properties: Array<TemplatePropertyDto>, plugins: Array<TemplatePluginDto>, memoryMb: MemoryRangeDto | null, notes: Array<string>, };
