// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestartPolicyDto = { enabled: boolean, maxAttempts: number, windowSecs: number, delaySecs: number, stableSecs: number, crashBackup: boolean, };
