// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RestorePreviewDto = { added: number, removed: number, changed: number, unchanged: number, changedJars: Array<string>, removedSample: Array<string>, totalBytes: number, containsSensitive: boolean, };
