// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectDto } from "./ProjectDto";

export type SearchPageDto = { hits: Array<ProjectDto>, total: number, };
