// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchRequestDto = { provider: string, text: string, 
/**
 * "relevance" | "downloads" | "updated"
 */
sort: string, offset: number, limit: number, };
