// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyDto } from "./PropertyDto";

export type ServerPropertiesDto = { fileExists: boolean, gameVersion: string, restartRequired: boolean, properties: Array<PropertyDto>, };
