// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ServerSoftwareDto = { softwareId: string, softwareName: string, gameVersion: string, build: string | null, jar: string, javaMinMajor: number | null, };
