// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricPointDto } from "./MetricPointDto";
import type { ProcessUsageDto } from "./ProcessUsageDto";
import type { TickSampleDto } from "./TickSampleDto";

export type ServerMetricsDto = { 
/**
 * Source: operating system process metrics of the server's process tree.
 */
current: ProcessUsageDto | null, history: Array<MetricPointDto>, uptimeMs: number | null, 
/**
 * Source: the server's own `tick query` or Paper `tps`/`mspt` commands.
 */
tick: TickSampleDto | null, tickHistory: Array<TickSampleDto>, 
/**
 * "vanilla_tick_query" | "paper_commands"; `None` = not available for this server.
 */
tickSource: string | null, };
