// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricPointDto } from "./MetricPointDto";
import type { ProcessUsageDto } from "./ProcessUsageDto";

export type ServerMetricsDto = { 
/**
 * Source: operating system process metrics of the server's process tree.
 */
current: ProcessUsageDto | null, history: Array<MetricPointDto>, uptimeMs: number | null, };
