// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanDto } from "./BanDto";
import type { KnownPlayerDto } from "./KnownPlayerDto";
import type { ListedPlayerDto } from "./ListedPlayerDto";
import type { OperatorDto } from "./OperatorDto";

export type ServerPlayersDto = { 
/**
 * Changes are sent to the running server through its console.
 */
live: boolean, readOnlyReason: string | null, onlineKnown: boolean, online: Array<string>, onlineMode: boolean, whitelistEnabled: boolean, enforceWhitelist: boolean, maxPlayers: number | null, operators: Array<OperatorDto>, whitelist: Array<ListedPlayerDto>, bans: Array<BanDto>, ipBans: Array<BanDto>, known: Array<KnownPlayerDto>, };
