// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosisDto } from "./DiagnosisDto";
import type { LaunchConfigDto } from "./LaunchConfigDto";
import type { ServerSoftwareDto } from "./ServerSoftwareDto";

export type ServerDto = { id: string, name: string, directory: string, software: ServerSoftwareDto, launch: LaunchConfigDto, 
/**
 * Lifecycle state (see `LifecycleState`), e.g. "running".
 */
state: string, pid: number | null, startedAt: number | null, readyAt: number | null, 
/**
 * Players seen joining in the console log since the last start.
 */
onlinePlayers: Array<string>, diagnosis: DiagnosisDto | null, lastExitCode: number | null, operations: Array<string>, consoleAttached: boolean, port: number | null, eulaAccepted: boolean, directoryExists: boolean, createdAt: number, };
