// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsDto = { 
/**
 * "system" | "dark" | "light"
 */
theme: string, trayNoticeShown: boolean, consoleBufferLines: number, quitStopTimeoutSecs: number, tickSampling: boolean, 
/**
 * Preset name, "system" or "#rrggbb".
 */
accent: string, onboardingCompleted: boolean, };
