// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SoftwareDto = { id: string, displayName: string, description: string, content: Array<string>, eulaRequired: boolean, supported: boolean, };
