// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuspectDto = { name: string, fileName: string, 
/**
 * "loader" (the stack frame names the jar) | "package"
 */
evidence: string, };
