// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskDto } from "./DiskDto";

export type SystemSnapshotDto = { cpuPercent: number, cpuCount: number, memoryTotalBytes: number, memoryUsedBytes: number, disks: Array<DiskDto>, osName: string, osVersion: string, hostName: string | null, };
