// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricPointDto } from "./MetricPointDto";
import type { SystemSnapshotDto } from "./SystemSnapshotDto";

export type SystemMetricsDto = { 
/**
 * Source: operating system (sysinfo).
 */
current: SystemSnapshotDto | null, history: Array<MetricPointDto>, };
