// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryRangeDto } from "./MemoryRangeDto";
import type { TemplatePluginDto } from "./TemplatePluginDto";
import type { TemplatePropertyDto } from "./TemplatePropertyDto";

export type TemplateDto = { id: string, name: string, description: string, icon: string, software: Array<string>, memoryMb: MemoryRangeDto | null, 
/**
 * Keys the template sets (values depend on the Minecraft version).
 */
propertyKeys: Array<string>, 
/**
 * Resolved default properties for modern versions (where until is None).
 */
defaultProperties: Array<TemplatePropertyDto>, backupIntervalMinutes: number | null, autoRestart: boolean, plugins: Array<TemplatePluginDto>, };
