// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextDocumentDto = { path: string, content: string, encoding: string, bom: boolean, 
/**
 * "lf" | "cr_lf" | "mixed" | "none"
 */
lineEnding: string, sha256: string, size: number, modified: number | null, lossy: boolean, readOnlyReason: string | null, truncated: boolean, };
