// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TickSampleDto = { at: number, tps: number | null, 
/**
 * TPS was calculated from MSPT (vanilla reports no TPS).
 */
tpsCalculated: boolean, mspt: number | null, 
/**
 * Vanilla P95 or Paper's 5-second maximum.
 */
msptHigh: number | null, status: string | null, };
