// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelLinkDto } from "./TunnelLinkDto";

export type TunnelStatusDto = { provider: string, displayName: string, installed: boolean, version: string | null, agentRunning: boolean | null, phase: string | null, secretConfigured: boolean | null, 
/**
 * "waiting" | "linked" | "failed" while or after a link started in MCPanel.
 */
linkState: string | null, linkClaimUrl: string | null, linkError: string | null, canControlAgent: boolean, canLink: boolean, canManageTunnels: boolean, links: Array<TunnelLinkDto>, };
