// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentVersionDto } from "./ContentVersionDto";

export type UpdateInfoDto = { fileName: string, name: string, currentVersion: string | null, latest: ContentVersionDto, };
