// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WriteTextDto = { content: string, encoding: string, bom: boolean, 
/**
 * Hash from when the document was opened; `null` to overwrite unconditionally.
 */
expectedSha256: string | null, };
