//! Server-link identity and credential model for future Minecraft server plugin integration.
//!
//! Separates Minecraft server plugin identity from user account identity (e.g. Microsoft/Google OAuth).
//! Provides secure enrollment tokens, revocable server credentials, scoped permissions,
//! and multi-host governance. See `docs/architecture/adr-009-server-linking.md`.

use crate::ids::ServerLinkId;
use secrecy::SecretString;
use serde::{Deserialize, Serialize};

/// Granular capability scopes for a linked Minecraft server.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ServerScope {
    /// Read-only access to console stream.
    ConsoleRead,
    /// Send commands into the server console.
    ConsoleWrite,
    /// Read telemetry: CPU, memory, TPS, MSPT, player counts.
    MetricsRead,
    /// Manage players: kick, ban, op, whitelist.
    PlayersManage,
    /// Power control: restart, stop, graceful shutdown.
    PowerControl,
    /// Read configuration files (read-only, secrets redacted).
    FilesRead,
    /// Trigger backup creation.
    BackupsTrigger,
}

impl ServerScope {
    pub const ALL: &[ServerScope] = &[
        ServerScope::ConsoleRead,
        ServerScope::ConsoleWrite,
        ServerScope::MetricsRead,
        ServerScope::PlayersManage,
        ServerScope::PowerControl,
        ServerScope::FilesRead,
        ServerScope::BackupsTrigger,
    ];
}

/// A short-lived, single-use enrollment pairing token generated by MCPanel
/// to pair a new Minecraft server running the MCPanel plugin.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerEnrollmentToken {
    /// Token string (e.g. "mcp_link_...").
    pub token: String,
    pub server_link_id: ServerLinkId,
    pub account_id: String,
    pub expires_at: i64,
    pub allowed_scopes: Vec<ServerScope>,
}

impl ServerEnrollmentToken {
    /// Generate a fresh enrollment token valid for `ttl_secs`.
    pub fn generate(
        server_link_id: ServerLinkId,
        account_id: impl Into<String>,
        ttl_secs: u64,
        allowed_scopes: Vec<ServerScope>,
    ) -> Self {
        use sha2::{Digest, Sha256};
        let now = jiff::Timestamp::now().as_second();
        let entropy = uuid::Uuid::now_v7();
        let mut hasher = Sha256::new();
        hasher.update(entropy.as_bytes());
        hasher.update(server_link_id.0.as_bytes());
        let token_hex = hex::encode(hasher.finalize());
        let token = format!("mcp_link_{}", &token_hex[..32]);

        Self {
            token,
            server_link_id,
            account_id: account_id.into(),
            expires_at: now + ttl_secs as i64,
            allowed_scopes,
        }
    }

    pub fn is_expired(&self, now_sec: i64) -> bool {
        now_sec >= self.expires_at
    }
}

/// Server authentication credentials given to the Minecraft server plugin upon successful pairing.
///
/// Kept separate from user identity (Microsoft/Google tokens are NEVER given to server plugins).
#[derive(Clone)]
pub struct ServerCredentialSecret {
    pub secret: SecretString,
    pub algorithm: String,
}

impl std::fmt::Debug for ServerCredentialSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ServerCredentialSecret")
            .field("algorithm", &self.algorithm)
            .field("secret", &"[REDACTED]")
            .finish()
    }
}

/// A Minecraft server instance enrolled and linked to an MCPanel account.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LinkedServerRecord {
    pub id: ServerLinkId,
    /// Owner's stable MCPanel account ID (independent of provider).
    pub account_id: String,
    /// Friendly display name (e.g. "SMP Survival Server").
    pub name: String,
    /// Cryptographic fingerprint of the server's identity key.
    pub fingerprint: String,
    /// Timestamp when paired.
    pub created_at: i64,
    /// Last heartbeat timestamp from server plugin.
    pub last_seen_at: Option<i64>,
    /// Authorized capability scopes for this server.
    pub scopes: Vec<ServerScope>,
    /// Revocation status.
    pub revoked: bool,
    pub revoked_at: Option<i64>,
}

impl LinkedServerRecord {
    pub fn new(
        id: ServerLinkId,
        account_id: impl Into<String>,
        name: impl Into<String>,
        fingerprint: impl Into<String>,
        scopes: Vec<ServerScope>,
        created_at: i64,
    ) -> Self {
        Self {
            id,
            account_id: account_id.into(),
            name: name.into(),
            fingerprint: fingerprint.into(),
            created_at,
            last_seen_at: Some(created_at),
            scopes,
            revoked: false,
            revoked_at: None,
        }
    }

    pub fn has_scope(&self, scope: ServerScope) -> bool {
        !self.revoked && self.scopes.contains(&scope)
    }

    pub fn revoke(&mut self, at_sec: i64) {
        self.revoked = true;
        self.revoked_at = Some(at_sec);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enrollment_token_lifecycle() {
        let server_id = ServerLinkId::new();
        let token = ServerEnrollmentToken::generate(
            server_id,
            "acc_user123",
            900,
            vec![ServerScope::ConsoleRead, ServerScope::MetricsRead],
        );

        assert!(token.token.starts_with("mcp_link_"));
        assert_eq!(token.server_link_id, server_id);
        assert_eq!(token.account_id, "acc_user123");
        assert!(!token.is_expired(token.expires_at - 10));
        assert!(token.is_expired(token.expires_at + 1));
    }

    #[test]
    fn linked_server_scope_enforcement_and_revocation() {
        let mut server = LinkedServerRecord::new(
            ServerLinkId::new(),
            "acc_user123",
            "Test SMP",
            "sha256:abc12345",
            vec![ServerScope::ConsoleRead, ServerScope::MetricsRead],
            1700000000,
        );

        assert!(server.has_scope(ServerScope::ConsoleRead));
        assert!(server.has_scope(ServerScope::MetricsRead));
        assert!(!server.has_scope(ServerScope::PowerControl));

        server.revoke(1700000500);
        assert!(server.revoked);
        assert_eq!(server.revoked_at, Some(1700000500));
        // Revoked server loses all capabilities:
        assert!(!server.has_scope(ServerScope::ConsoleRead));
    }
}
